type Option = {
  value: string;
  label: string;
};

type TranslateFunction = (key: string) => string;

export const getOptions = (t: TranslateFunction): Option[] => [
  { value: "facts/", label: t("message.factAll") },
  { value: "fact1/", label: t("message.fact1NameChange") },
  { value: "fact2/", label: t("message.fact2AddressChange") },
  { value: "fact3/", label: t("message.fact3Reorganization") },
  { value: "fact4/", label: t("message.fact4ActivitySuspension") },
  { value: "fact5/", label: t("message.fact5ActivityTermination") },
  { value: "fact6/", label: t("message.fact6ManagementDecisions") },
  { value: "fact7/", label: t("message.fact7SecuritiesRightsChange") },
  { value: "fact8/", label: t("message.fact8ManagementChanges") },
  { value: "fact9/", label: t("message.fact9BranchListChanges") },
  { value: "fact10/", label: t("message.fact10RepresentativeListChanges") },
  { value: "fact11/", label: t("message.fact11SubsidiaryListChanges") },
  { value: "fact12/", label: t("message.fact12DependentCompanyListChanges") },
  { value: "fact13/", label: t("message.fact13PropertyOrBankAccountArrest") },
  { value: "fact14/", label: t("message.fact14ClaimAgainstIssuerOver10PercentAssets") },
  { value: "fact15/", label: t("message.fact15LoanOver50PercentCapital") },
  { value: "fact16/", label: t("message.fact16LoanOver50PercentAssets") },
  { value: "fact17/", label: t("message.fact17IncreaseInAssetValueOver10Percent") },
  { value: "fact18/", label: t("message.fact18DecreaseInAssetValueOver10Percent") },
  { value: "fact19/", label: t("message.fact19DealOver10PercentAssets") },
  { value: "fact20/", label: t("message.fact20LargeTransaction") },
  { value: "fact21/", label: t("message.fact21TransactionWithAffiliate") },
  { value: "fact22/", label: t("message.fact22LicenseAcquisition") },
  { value: "fact23/", label: t("message.fact23LicenseAnnulmentOrTermination") },
  { value: "fact24/", label: t("message.fact24LicenseSuspension") },
  { value: "fact25/", label: t("message.fact25SecuritiesIssuance") },
  { value: "fact26/", label: t("message.fact26SecuritiesIssuanceSuspension") },
  { value: "fact27/", label: t("message.fact27SecuritiesIssuanceResumption") },
  { value: "fact28/", label: t("message.fact28SecuritiesIssuanceRecognitionAsFailed") },
  { value: "fact29/", label: t("message.fact29SecuritiesIssuanceRecognitionAsInvalid") },
  { value: "fact30/", label: t("message.fact30OwnershipChangeOver10PercentShares") },
  { value: "fact31/", label: t("message.fact31SecuritiesExecutionTerms") },
  { value: "fact32/", label: t("message.fact32SecuritiesIncomeAccrual") },
  { value: "fact33/", label: t("message.fact33BankruptcyProcedure") },
  { value: "fact34/", label: t("message.fact34ManagementShareOwnershipChange") },
  { value: "fact35/", label: t("message.fact35OwnershipChangeInExecutiveOrgShares") },
  { value: "fact36/", label: t("message.fact36AffiliateListChanges") },
  { value: "fact37/", label: t("message.fact37RightToRedeemSecuritiesByIssuer") },
  { value: "fact38/", label: t("message.fact38SecuritiesListingOnMarkets") },
  { value: "fact39/", label: t("message.fact39SecuritiesDelistingFromMarkets") },
  { value: "fact40/", label: t("message.fact40ChangesInSecuritiesIssuanceResolution") },
  { value: "fact41/", label: t("message.fact41ManagementRecommendationOnDividendPayments") },
  { value: "fact42/", label: t("message.fact42DividendPayments") },
  { value: "fact43/", label: t("message.fact43OwnershipOf35PercentShares") },
  { value: "fact44/", label: t("message.fact44AcquisitionOfSharesOver20PercentCapital") },
  { value: "fact45/", label: t("message.fact45OfferToBuySharesByShareholderOver50Percent") },
  { value: "fact46/", label: t("message.fact46ShortName") },
];
